services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - ./persistent_volume:/app/persistent_volume       # Volumen para la base de datos SQLite, auth y logs
